// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzjoxlIWfIllT5hi5srEWF2wiHh1b93fw',
    appId: '1:1012428499740:web:1e0e0790ec2930dafb68d9',
    messagingSenderId: '1012428499740',
    projectId: 'barbershop-line',
    authDomain: 'barbershop-line.firebaseapp.com',
    storageBucket: 'barbershop-line.firebasestorage.app',
    measurementId: 'G-GJ2JCVCWWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVsGzaH3xEhdPSoZnkmJ908P6DGv0_Pgs',
    appId: '1:1012428499740:android:c700061331fbfd57fb68d9',
    messagingSenderId: '1012428499740',
    projectId: 'barbershop-line',
    storageBucket: 'barbershop-line.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwCvJLnFguQqx5LuxJvfDK1BYuxQ-V24g',
    appId: '1:1012428499740:ios:afbdc342be9f0c66fb68d9',
    messagingSenderId: '1012428499740',
    projectId: 'barbershop-line',
    storageBucket: 'barbershop-line.firebasestorage.app',
    iosBundleId: 'com.example.barbershop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwCvJLnFguQqx5LuxJvfDK1BYuxQ-V24g',
    appId: '1:1012428499740:ios:afbdc342be9f0c66fb68d9',
    messagingSenderId: '1012428499740',
    projectId: 'barbershop-line',
    storageBucket: 'barbershop-line.firebasestorage.app',
    iosBundleId: 'com.example.barbershop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzjoxlIWfIllT5hi5srEWF2wiHh1b93fw',
    appId: '1:1012428499740:web:fe2e3c3e8db85676fb68d9',
    messagingSenderId: '1012428499740',
    projectId: 'barbershop-line',
    authDomain: 'barbershop-line.firebaseapp.com',
    storageBucket: 'barbershop-line.firebasestorage.app',
    measurementId: 'G-2YD94TKK0D',
  );
}
